remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
title: GW McElfresh ![>](/images/self/headshot.jpg)
description: Computational Biology PhD 
location: Center for Computational Biology, University of Kansas
