remote_theme: pages-themes/tactile@v0.2.0
theme: jekyll-theme-tactile
title: GW McElfresh <img src="https://raw.githubusercontent.com/GWMcElfresh/GWMcElfresh.github.io/master/images/self/headshot.jpg" align="right">
description: Computational Biology PhD 
location: Center for Computational Biology, University of Kansas
